import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@Styles/globals.scss";
import Header from "@Components/common/header";
import StoreProvider from "@App/store/StoreProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <header>
            <Header />
          </header>
          <main>{children}</main>
          <footer></footer>
        </body>
      </html>
    </StoreProvider>
  );
}
